### ISSUE TITLE
Todo produto deve ter um preço

### ISSUE THREAD

**Issue by kyriri** [TreinaDev/e-commerce-td08-time01#24]
_Eu, como desenvolvedor do sistema,
quero que todo produto tenha que ter um preço
para diminuir bugs_

**Definition of done**
- [ ] não é possível criar, via console, um produto que não tenha um preço associado
- [ ] o erro que isso gera é claro para o dev sobre a falta de preço inicial e como corrigi-la
- [ ] mas ainda assim o produto é instância de Product e seu primeiro preço é instância de Price

**Ideias que surgiram quando essa questão foi levantada**
E se isto desse erro:
`Product.create(bla bla)`

mas existisse algo assim:
`Product.create(bla bla).with_inicial_price(15)`

**Comment by kyriri** [comment]
Esta issue ainda não foi implementada. Manter fechada?
